### ISSUE TITLE
Downloading attachments via shortcode fails with 401 error

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#679]
A customer reported that if he tries to purchase an attachment via the shortcode [laterpay_premium_download], only an empty page is displayed after the purchase.
I tried with the current release (0.9.11.2): The respective ajax request fails with a 401 (Unauthorized).

**Comment by AliaksandrVahura-ScienceSoft** [comment]
I've got error 403 on my local (no access). Somehow request to the laterpay if we have access for purcahsed file returned false. After post reload i've got access to the purchased file. Second purchase was successfull.

**Comment by twoldrich** [comment]
The customer just replied that purchasing the item a second time, it worked for him.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Same for us.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Which status of this issue?

**Comment by twoldrich** [comment]
This issue still appears, both in test and live mode:
- The very first time, I purchase an attachment via shortcode, the ajax request fails with "forbidden" and a white screen is displayed.
- I have to manually go back, purchase again and see the message "You already bought this".
- Then, the download starts and the shortcode button switches to "download now".
- All further shortcode purchases work fine.

@AliaksandrVahura-ScienceSoft Is currently looking into this again.

**Comment by twoldrich** [comment]
We received two new bug reports from users today concerning this issue:
Downloading an attachement fails for both of them with an empty page.
(I advised them to reload the page and click the purchase button again – I'll comment once I got their replies.)

**Comment by twoldrich** [comment]
We didn't get responses on those mentioned issues so far. For me the attachement download works, once I purchase a second (not the same) item after the failed purchase. I tried it when I was logged-in to my user account.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Fixed with #780.

**Comment by twoldrich** [comment]
According to our discussion in the development channel, I would tend to reopen this issue:
There seems to be still an issue with downloading such attachments and getting a "404".

**Comment by mturalenka** [comment]
this issue was closed, and was due to differences in URLs encoding/verification mechanism between LP API and plugin: ts and hmac.
